const assert = require('node:assert/strict');
const { western, parse, format, stocksCalc, resolveClasses, shareSnapshot } = require('./v2/designer-core.js');
assert.equal(western('١٢٣٤٥٦٧٨٩٠ / ۱۲۳۴۵۶۷۸۹۰'), '1234567890 / 1234567890');
for (const value of ['100000','١٠٠٠٠٠','۱۰۰۰۰۰','100,000','١٠٠٬٠٠٠']) assert.equal(parse(value), 100000);
assert.equal(parse('١٢٫٥٠'), 12.5);
for (const value of ['', '1e3', '100abc', '10,00', '1.234', 'Infinity', '1000000000001']) assert.ok(Number.isNaN(parse(value)), value);
assert.equal(format(100/3), '33.33');
const founder = {id:'f',categoryMode:'new',categoryName:'Founders',rights:'10 votes',count:'٦٠٠',value:'10',votesPerShare:'10'};
const linked = {id:'l',categoryMode:'existing',categoryId:'f',count:'100',value:'10',votesPerShare:1};
const investor = {id:'i',categoryMode:'none',count:'300',value:'10',votesPerShare:'1'};
let result=stocksCalc([founder, linked, investor]);
assert.equal(result.totalValue,10000);assert.equal(result.totalVotes,7300);assert.equal(result.rows[1].votes,1000);assert.equal(result.rows[0].ownership,60);assert.equal(result.invalid,false);
assert.equal(stocksCalc([{...founder,votesPerShare:'5'},linked]).rows[1].votes,500);
assert.equal(resolveClasses([{...founder,categoryName:'Renamed'},linked])[1].existingCategory,'Renamed');
assert.equal(stocksCalc([linked]).invalid,true);
assert.equal(stocksCalc([founder,{...linked,missingCategory:true}]).invalid,false);
assert.equal(stocksCalc([founder,{...founder,id:'duplicate'}]).duplicateNames,true);
assert.equal(stocksCalc([{...investor,count:'1.5'}]).invalid,true);
assert.equal(stocksCalc([{...investor,count:'abc'}]).invalid,true);
assert.equal(stocksCalc([{...investor,count:3,value:'0.10',votesPerShare:0}]).totalValue,0.3);
assert.equal(stocksCalc([{...investor,votesPerShare:0}]).rows[0].voteShare,0);
const source={capital:{bank:'Private bank'},stocks:[founder],dealEngineering:{draft:{}},partnership:{exit:'Private terms'},versions:[{data:{}}]};
const restricted=shareSnapshot(source,'capital'),full=shareSnapshot(source,'full');
assert.equal(restricted.capital.bank,'');assert.ok(!restricted.dealEngineering&&!restricted.partnership&&!restricted.versions);
assert.equal(full.capital.bank,'Private bank');assert.ok(full.partnership&&!full.versions);assert.equal(source.versions.length,1);
console.log('Designer regressions passed: numeral normalization, invalid drafts, class inheritance, voting, decimal money and selective sharing.');
